### ISSUE TITLE
update module for parser

### ISSUE THREAD

**Issue by prabalchhatkuli** [saksham1991999/GitTra#1]
Found a module comment-parser. But it needs updating for unicode and multiline comments.

**Comment by prabalchhatkuli** [comment]
Parser module does not cover multiline comment

**Comment by prabalchhatkuli** [comment]
Python multiline comments have been left alone for now, because they are doc strings, it is hard to evaluate doc strings from string literals.

**Comment by saksham1991999** [comment]
> 
> 
> Python multiline comments have been left alone for now, because they are docstrings, it is hard to evaluate docstrings from string literals.

Can we access the DocStrings using .\__doc\__?
Here's a link for your reference https://www.geeksforgeeks.org/python-docstrings/

**Comment by prabalchhatkuli** [comment]
> > Python multiline comments have been left alone for now, because they are docstrings, it is hard to evaluate docstrings from string literals.
> 
> Can we access the DocStrings using .__doc__?
> Here's a link for your reference https://www.geeksforgeeks.org/python-docstrings/

Yes, but it only gives us the comment. But we would need the exact point the file where the comment ends and where it begins.

**Comment by prabalchhatkuli** [comment]
completed
